kind: pipeline
type: docker
name: javadocs-deploy

trigger:
  event:
    - push
    - custom

steps:
  - name: javadoc
    image: gradle:jdk21
    commands:
      - gradle javadoc
    when:
      branch:
        - ${DRONE_REPO_BRANCH}

  - name: deploy
    image: drillster/drone-rsync
    settings:
      source: build/docs/javadoc/
      target:
        from_secret: deploy_target
      hosts:
        from_secret: deploy_host
      user: drone
      key:
        from_secret: ssh_key
      port: 22
      delete: true
      recursive: true
    when:
      branch:
        - ${DRONE_REPO_BRANCH}