kind: pipeline
type: docker
name: javadocs-deploy

trigger:
  branch:
    - 1.21.4
  event:
    - push
    - custom

steps:
  - name: javadoc
    image: gradle:jdk21
    commands:
      - gradle javadoc

  - name: deploy
    image: drillster/drone-rsync
    settings:
      source: build/docs/javadoc
      target:
        from_secret: deploy_target
      hosts:
        from_secret: deploy_host
      user: drone
      key:
        from_secret: ssh_key
      port: 22
      delete: true
      recursive: true